// Generated by scripts/provision-authority.mjs. It contains no private key material.
export const LICENSE_PUBLIC_KEY_JWK: JsonWebKey = {
  "kty": "EC",
  "x": "0Icpm1DsxRgV0GxMG31iWqXQqRdalgjP_qr8NHqcCCA",
  "y": "nA5Ee3b95-AXU2Vj3yoQkL2So6edAhBHxyiLilmu2Ps",
  "crv": "P-256"
};
