import { LICENSE_PUBLIC_KEY_JWK } from "./license-public-key";

export const ANDROID_LICENSE_PRODUCT_ID = "WHOLESALE_POS_ANDROID";

export type ActivationPayload = {
  format: "WPOS-LICENSE";
  version: 1;
  licenseId: string;
  deviceId: string;
  productId: string;
  productName: string;
  productVersion: string;
  edition: string;
  issuedAt: string;
};

function canonicalPayload(payload: ActivationPayload) {
  return JSON.stringify({ format: payload.format, version: payload.version, licenseId: payload.licenseId, deviceId: payload.deviceId, productId: payload.productId, productName: payload.productName, productVersion: payload.productVersion, edition: payload.edition, issuedAt: payload.issuedAt });
}

function decodeBase64Url(value: string) {
  if (!/^[A-Za-z0-9_-]+$/.test(value)) throw new Error("Activation code contains invalid characters.");
  const padded = value.replaceAll("-", "+").replaceAll("_", "/").padEnd(Math.ceil(value.length / 4) * 4, "=");
  const binary = atob(padded);
  return Uint8Array.from(binary, (character) => character.charCodeAt(0));
}

/** Parses a QR payload generated by the private License Manager. */
export function parseActivationQr(value: string) {
  const parsed = JSON.parse(value) as { deviceId?: unknown; activationCode?: unknown };
  if (typeof parsed.deviceId !== "string" || typeof parsed.activationCode !== "string") throw new Error("This QR code is not a WholesalePOS activation.");
  return { deviceId: parsed.deviceId.trim().toUpperCase(), activationCode: parsed.activationCode.trim() };
}

/** Verifies an offline activation signature, product, Device ID, and issue timestamp. */
export async function verifyOfflineActivation(code: string, expectedDeviceId: string, publicKeyJwk: JsonWebKey = LICENSE_PUBLIC_KEY_JWK) {
  if (code.length > 4096) throw new Error("Activation code is too long.");
  const [prefix, payloadPart, signaturePart, extra] = code.trim().split(".");
  if (prefix !== "WPOS1" || !payloadPart || !signaturePart || extra) throw new Error("Activation code format is invalid.");
  if (!publicKeyJwk.x || !publicKeyJwk.y) throw new Error("This Android build is not connected to a signing authority.");
  const payloadBytes = decodeBase64Url(payloadPart);
  const signature = decodeBase64Url(signaturePart);
  if (signature.length !== 64) throw new Error("Activation signature is invalid.");
  const key = await crypto.subtle.importKey("jwk", publicKeyJwk, { name: "ECDSA", namedCurve: "P-256" }, false, ["verify"]);
  const valid = await crypto.subtle.verify({ name: "ECDSA", hash: "SHA-256" }, key, signature, payloadBytes);
  if (!valid) throw new Error("Activation signature is invalid.");
  const payloadText = new TextDecoder().decode(payloadBytes);
  const payload = JSON.parse(payloadText) as ActivationPayload;
  if (payload.format !== "WPOS-LICENSE" || payload.version !== 1 || canonicalPayload(payload) !== payloadText) throw new Error("Activation payload is invalid.");
  if (payload.productId !== ANDROID_LICENSE_PRODUCT_ID) throw new Error("This activation is for a different product.");
  if (payload.deviceId !== expectedDeviceId.trim().toUpperCase()) throw new Error("This activation code belongs to a different tablet.");
  const issuedAt = Date.parse(payload.issuedAt);
  if (!Number.isFinite(issuedAt) || issuedAt > Date.now() + 5 * 60_000) throw new Error("Activation date is invalid.");
  return payload;
}
