import { LICENSE_PUBLIC_KEY_JWK } from "./license-public-key";

export const ANDROID_LICENSE_PRODUCT_ID = "WHOLESALE_POS_ANDROID";
export const LICENSE_CLOCK_TOLERANCE_MS = 5 * 60_000;
export type LicenseType = "MONTHLY" | "YEARLY" | "LIFETIME";

export type LegacyActivationPayload = {
  format: "WPOS-LICENSE";
  version: 1;
  licenseId: string;
  deviceId: string;
  productId: string;
  productName: string;
  productVersion: string;
  edition: string;
  issuedAt: string;
};

export type RenewableActivationPayload = {
  format: "WPOS-LICENSE";
  version: 2;
  licenseId: string;
  licenseSerialNumber: string;
  customerId: string;
  deviceId: string;
  productId: string;
  productName: string;
  productVersion: string;
  edition: string;
  licenseType: LicenseType;
  issuedAt: string;
  expiresAt: string | null;
};

export type ActivationPayload = LegacyActivationPayload | RenewableActivationPayload;

/** Carries a stable internal reason while keeping user-facing validation messages non-technical. */
export class LicenseValidationError extends Error {
  constructor(public readonly reason: "INVALID" | "EXPIRED", message: string, public readonly payload: ActivationPayload | null = null) {
    super(message);
    this.name = "LicenseValidationError";
  }
}

function canonicalPayload(payload: ActivationPayload) {
  if (payload.version === 2) {
    return JSON.stringify({ format: payload.format, version: payload.version, licenseId: payload.licenseId, licenseSerialNumber: payload.licenseSerialNumber, customerId: payload.customerId, deviceId: payload.deviceId, productId: payload.productId, productName: payload.productName, productVersion: payload.productVersion, edition: payload.edition, licenseType: payload.licenseType, issuedAt: payload.issuedAt, expiresAt: payload.expiresAt });
  }
  return JSON.stringify({ format: payload.format, version: payload.version, licenseId: payload.licenseId, deviceId: payload.deviceId, productId: payload.productId, productName: payload.productName, productVersion: payload.productVersion, edition: payload.edition, issuedAt: payload.issuedAt });
}

function decodeBase64Url(value: string) {
  if (!/^[A-Za-z0-9_-]+$/.test(value)) throw new LicenseValidationError("INVALID", "Activation code is invalid.");
  const padded = value.replaceAll("-", "+").replaceAll("_", "/").padEnd(Math.ceil(value.length / 4) * 4, "=");
  const binary = atob(padded);
  return Uint8Array.from(binary, (character) => character.charCodeAt(0));
}

function validatePayload(payload: ActivationPayload, payloadText: string) {
  if (payload.format !== "WPOS-LICENSE" || ![1, 2].includes(payload.version) || canonicalPayload(payload) !== payloadText) throw new LicenseValidationError("INVALID", "Activation code is invalid.");
  if (payload.version === 2 && (!payload.licenseSerialNumber || !payload.customerId || !["MONTHLY", "YEARLY", "LIFETIME"].includes(payload.licenseType) || (payload.licenseType === "LIFETIME" ? payload.expiresAt !== null : !payload.expiresAt))) throw new LicenseValidationError("INVALID", "Activation code is invalid.");
}

/** Returns the signed plan while treating backward-compatible version 1 codes as lifetime. */
export function licenseTypeOf(payload: ActivationPayload): LicenseType {
  return payload.version === 2 ? payload.licenseType : "LIFETIME";
}

/** Returns the signed expiration timestamp, or null for lifetime and legacy activations. */
export function expirationOf(payload: ActivationPayload) {
  return payload.version === 2 ? payload.expiresAt : null;
}

/** Returns the number of calendar display days remaining without allowing a negative value. */
export function daysRemaining(expiresAt: string | null, nowMs = Date.now()) {
  return expiresAt === null ? null : Math.max(0, Math.ceil((Date.parse(expiresAt) - nowMs) / (24 * 60 * 60 * 1000)));
}

/** Parses a QR payload generated by the private License Manager. */
export function parseActivationQr(value: string) {
  const parsed = JSON.parse(value) as { deviceId?: unknown; activationCode?: unknown };
  if (typeof parsed.deviceId !== "string" || typeof parsed.activationCode !== "string") throw new Error("This QR code is not a Suki Sync activation.");
  return { deviceId: parsed.deviceId.trim().toUpperCase(), activationCode: parsed.activationCode.trim() };
}

/** Verifies the signature and every signed device, product, version, issue, and expiration claim. */
export async function verifyOfflineActivation(code: string, expectedDeviceId: string, publicKeyJwk: JsonWebKey = LICENSE_PUBLIC_KEY_JWK, nowMs = Date.now()) {
  if (code.length > 4096) throw new LicenseValidationError("INVALID", "Activation code is invalid.");
  const [prefix, payloadPart, signaturePart, extra] = code.trim().split(".");
  if (prefix !== "WPOS1" || !payloadPart || !signaturePart || extra) throw new LicenseValidationError("INVALID", "Activation code format is invalid.");
  if (!publicKeyJwk.x || !publicKeyJwk.y) throw new LicenseValidationError("INVALID", "This Android build is not connected to a license authority.");
  const payloadBytes = decodeBase64Url(payloadPart);
  const signature = decodeBase64Url(signaturePart);
  if (signature.length !== 64) throw new LicenseValidationError("INVALID", "Activation code is invalid.");
  const key = await crypto.subtle.importKey("jwk", publicKeyJwk, { name: "ECDSA", namedCurve: "P-256" }, false, ["verify"]);
  const valid = await crypto.subtle.verify({ name: "ECDSA", hash: "SHA-256" }, key, signature, payloadBytes);
  if (!valid) throw new LicenseValidationError("INVALID", "Activation code is invalid.");
  const payloadText = new TextDecoder().decode(payloadBytes);
  let payload: ActivationPayload;
  try { payload = JSON.parse(payloadText) as ActivationPayload; }
  catch { throw new LicenseValidationError("INVALID", "Activation code is invalid."); }
  validatePayload(payload, payloadText);
  if (payload.productId !== ANDROID_LICENSE_PRODUCT_ID) throw new LicenseValidationError("INVALID", "This activation is for a different product.");
  if (payload.deviceId !== expectedDeviceId.trim().toUpperCase()) throw new LicenseValidationError("INVALID", "This activation code belongs to a different tablet.");
  const issuedAt = Date.parse(payload.issuedAt);
  if (!Number.isFinite(issuedAt) || issuedAt > nowMs + LICENSE_CLOCK_TOLERANCE_MS) throw new LicenseValidationError("INVALID", "Activation date is invalid.");
  const expiresAt = expirationOf(payload);
  if (expiresAt !== null) {
    const expiration = Date.parse(expiresAt);
    if (!Number.isFinite(expiration) || expiration <= issuedAt) throw new LicenseValidationError("INVALID", "Activation expiration is invalid.");
    if (nowMs > expiration) throw new LicenseValidationError("EXPIRED", "Your license has expired.", payload);
  }
  return payload;
}
