import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Archive, DatabaseBackup as Backup, Building2, Check, Clock3, Download, FileDown, FileSpreadsheet, History, KeyRound, Lock, LockKeyhole, PackagePlus, Pencil, Plus, Printer, RefreshCw, Replace, Search, Settings, ShieldCheck, X } from "lucide-react";
import QRCode from "qrcode";
import type { AppLockStatus, CreateLicenseInput, LicenseDisplayStatus, LicenseListItem, LicenseStatus, LicenseType, LicensedProduct, ManagerSnapshot } from "../shared/contracts";

type Tab = "licenses" | "history" | "settings";
type Toast = { message: string; tone: "success" | "error" };

const blankLicense: CreateLicenseInput = { customerName: "", businessName: "", contactNumber: "", email: "", customerNotes: "", deviceId: "", productId: "WHOLESALE_POS_ANDROID", appVersion: "0.7.0", licenseNotes: "", licenseType: "LIFETIME" };

/** Renders the password-gated desktop license administration application. */
export function App() {
  const [status, setStatus] = useState<AppLockStatus | null>(null);
  const [snapshot, setSnapshot] = useState<ManagerSnapshot | null>(null);
  const [busy, setBusy] = useState(false);
  const [toast, setToast] = useState<Toast | null>(null);
  const [tab, setTab] = useState<Tab>("licenses");
  const [selected, setSelected] = useState<LicenseListItem | null>(null);

  useEffect(() => { void window.licenseManager.status().then(setStatus); return window.licenseManager.onAutoLocked(() => { setSnapshot(null); setSelected(null); setStatus((current) => current ? { ...current, unlocked: false } : current); setToast({ message: "License Manager locked after inactivity.", tone: "success" }); }); }, []);
  useEffect(() => {
    if (!snapshot) return;
    let lastTouch = 0;
    const touch = () => { const current = Date.now(); if (current - lastTouch < 30_000) return; lastTouch = current; void window.licenseManager.touch(); };
    window.addEventListener("pointerdown", touch); window.addEventListener("keydown", touch);
    return () => { window.removeEventListener("pointerdown", touch); window.removeEventListener("keydown", touch); };
  }, [snapshot]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 4500); return () => window.clearTimeout(timer); }, [toast]);

  async function run<T>(operation: () => Promise<T>, success?: string) {
    setBusy(true);
    try { const result = await operation(); if (success) setToast({ message: success, tone: "success" }); return result; }
    catch (error) { setToast({ message: error instanceof Error ? error.message : "The operation failed.", tone: "error" }); return undefined; }
    finally { setBusy(false); }
  }

  async function refresh() { const next = await run(() => window.licenseManager.snapshot()); if (next) { setSnapshot(next); if (selected) setSelected(next.licenses.find((license) => license.id === selected.id) ?? null); } }
  async function lock() { await window.licenseManager.lock(); setSnapshot(null); setSelected(null); setStatus((current) => current ? { ...current, unlocked: false } : current); }

  if (!status) return <main className="center-page"><RefreshCw className="spin" size={30} /><strong>Opening private license database</strong></main>;
  if (!status.provisioned || !status.unlocked || !snapshot) return <AccessScreen status={status} busy={busy} run={run} onReady={(next) => { setSnapshot(next); setStatus({ provisioned: true, unlocked: true, bootstrapReady: false }); }} />;

  return <div className="manager-shell">
    <aside className="side-nav"><div className="brand"><span><ShieldCheck size={23} /></span><div><strong>License Manager</strong><small>Private authority</small></div></div>
      <nav>{([ ["licenses", KeyRound, "Licenses"], ["history", History, "History"], ["settings", Settings, "Settings"] ] as const).map(([id, Icon, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}><Icon size={20} />{label}</button>)}</nav>
      <div className="authority"><small>Authority fingerprint</small><code>{snapshot.publicKeyFingerprint}</code><button onClick={() => void lock()}><Lock size={17} /> Lock now</button></div>
    </aside>
    <main className="workspace">
      {tab === "licenses" ? <Licenses snapshot={snapshot} selected={selected} setSelected={setSelected} busy={busy} run={run} refresh={refresh} /> : null}
      {tab === "history" ? <HistoryView snapshot={snapshot} /> : null}
      {tab === "settings" ? <SettingsView snapshot={snapshot} busy={busy} run={run} refresh={refresh} /> : null}
    </main>
    {toast ? <div className={`toast ${toast.tone}`}>{toast.message}</div> : null}
  </div>;
}

function AccessScreen({ status, busy, run, onReady }: { status: AppLockStatus; busy: boolean; run: <T>(operation: () => Promise<T>, success?: string) => Promise<T | undefined>; onReady: (snapshot: ManagerSnapshot) => void }) {
  const [password, setPassword] = useState("");
  const [companyName, setCompanyName] = useState("WholesalePOS");
  const [contactInformation, setContactInformation] = useState("");
  const [restorePassword, setRestorePassword] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); const result = status.provisioned ? await run(() => window.licenseManager.unlock(password)) : await run(() => window.licenseManager.setup({ password, companyName, contactInformation })); if (result) onReady(result); }
  async function restore() { const result = await run(() => window.licenseManager.restoreBackup(restorePassword)); if (result) onReady(result); }
  return <main className="access-page"><section className="access-panel"><div className="access-mark"><ShieldCheck size={31} /></div><p className="eyebrow">Private owner application</p><h1>{status.provisioned ? "Unlock License Manager" : "Secure authority setup"}</h1><p className="muted">The signing key and customer database remain encrypted and offline on this Windows account.</p>
    <form className="form-stack" onSubmit={submit}>{!status.provisioned ? <><label>Company name<input value={companyName} onChange={(event) => setCompanyName(event.target.value)} required /></label><label>Contact information<textarea value={contactInformation} onChange={(event) => setContactInformation(event.target.value)} rows={2} /></label></> : null}<label>Administrator password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength={12} required autoFocus /></label><button className="button primary" disabled={busy || (!status.provisioned && !status.bootstrapReady)}><LockKeyhole size={18} /> {busy ? "Please wait" : status.provisioned ? "Unlock" : "Create encrypted vault"}</button></form>
    {!status.provisioned && !status.bootstrapReady ? <p className="warning">Signing authority is not provisioned on this Windows account. Restore an encrypted backup, or run the owner provisioning command before setup.</p> : null}
    {!status.provisioned ? <div className="restore-box"><strong>Recover after a PC reinstall</strong><label>Backup password<input type="password" value={restorePassword} onChange={(event) => setRestorePassword(event.target.value)} minLength={12} /></label><button className="button secondary" disabled={busy || restorePassword.length < 12} onClick={() => void restore()}><Backup size={18} /> Restore encrypted backup</button></div> : null}
  </section></main>;
}

function Licenses({ snapshot, selected, setSelected, busy, run, refresh }: { snapshot: ManagerSnapshot; selected: LicenseListItem | null; setSelected: (license: LicenseListItem | null) => void; busy: boolean; run: <T>(operation: () => Promise<T>, success?: string) => Promise<T | undefined>; refresh: () => Promise<void> }) {
  const [search, setSearch] = useState(""); const [sort, setSort] = useState("date-desc"); const [createOpen, setCreateOpen] = useState(false); const [duplicate, setDuplicate] = useState<LicenseListItem | null>(null); const [replaceTarget, setReplaceTarget] = useState<LicenseListItem | null>(null); const [renewTarget, setRenewTarget] = useState<LicenseListItem | null>(null); const [issued, setIssued] = useState<LicenseListItem | null>(null);
  const filtered = useMemo(() => { const needle = search.toLowerCase().trim(); const rows = snapshot.licenses.filter((license) => !needle || [license.customer.customerName, license.customer.businessName, license.deviceId, license.activationCode, license.licenseSerialNumber].some((value) => value.toLowerCase().includes(needle))); return rows.sort((a, b) => sort === "customer" ? a.customer.customerName.localeCompare(b.customer.customerName) : sort === "status" ? a.displayStatus.localeCompare(b.displayStatus) : sort === "date-asc" ? a.issueDate.localeCompare(b.issueDate) : b.issueDate.localeCompare(a.issueDate)); }, [search, snapshot.licenses, sort]);
  async function create(input: CreateLicenseInput) { const result = await run(() => window.licenseManager.createLicense(input)); if (!result) return; setCreateOpen(false); if (result.kind === "DUPLICATE") { setDuplicate(result.existing); setSelected(result.existing); } else { setIssued(result.license); setSelected(result.license); await refresh(); } }
  async function reissue(license: LicenseListItem) { const result = await run(() => window.licenseManager.reissueLicense(license.id, "Secure reissue requested by administrator."), "Original activation code reissued."); if (result) { setIssued(result); setDuplicate(null); await refresh(); } }
  return <section className="screen"><header className="screen-header"><div><p className="eyebrow">Customer database</p><h1>Licenses</h1><p>Generate, locate, reissue, replace, and document offline activations.</p></div><button className="button primary" onClick={() => setCreateOpen(true)}><Plus size={18} /> New license</button></header>
    <div className="toolbar"><label className="search"><Search size={18} /><input placeholder="Search customer, business, device, or activation code" value={search} onChange={(event) => setSearch(event.target.value)} /></label><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="date-desc">Newest activation</option><option value="date-asc">Oldest activation</option><option value="customer">Customer name</option><option value="status">License status</option></select><span>{filtered.length} records</span></div>
    <div className="license-layout"><div className="table-panel"><table><thead><tr><th>Customer</th><th>License</th><th>Device ID</th><th>Issue date</th><th>Expiration</th><th>Remaining</th><th>Status</th></tr></thead><tbody>{filtered.map((license) => <tr key={license.id} className={selected?.id === license.id ? "selected" : ""} onClick={() => setSelected(license)}><td><strong>{license.customer.customerName}</strong><small>{license.customer.businessName}</small></td><td>{formatLicenseType(license.licenseType)}<small>{license.productName}</small></td><td><code>{license.deviceId}</code></td><td>{formatDate(license.issueDate)}</td><td>{license.expirationDate ? formatDate(license.expirationDate) : "Lifetime"}</td><td>{license.daysRemaining === null ? "Unlimited" : `${license.daysRemaining} days`}</td><td><StatusBadge status={license.displayStatus} /></td></tr>)}</tbody></table>{filtered.length === 0 ? <Empty icon={Search} text="No licenses match this search." /> : null}</div>
      <LicenseDetails license={selected} busy={busy} run={run} refresh={refresh} onRenew={() => selected && setRenewTarget(selected)} onReplace={() => selected && setReplaceTarget(selected)} onReissue={() => selected && void reissue(selected)} /></div>
    {createOpen ? <CreateLicenseDialog products={snapshot.products} customers={snapshot.customers} onClose={() => setCreateOpen(false)} onCreate={create} busy={busy} /> : null}
    {duplicate ? <Dialog title="Device already licensed" onClose={() => setDuplicate(null)}><p><strong>{duplicate.deviceId}</strong> already belongs to {duplicate.customer.customerName}. No duplicate was created.</p><div className="dialog-actions"><button className="button secondary" onClick={() => { setSelected(duplicate); setDuplicate(null); }}>View existing</button><button className="button secondary" onClick={() => void reissue(duplicate)}>Reissue same code</button><button className="button primary" onClick={() => { setReplaceTarget(duplicate); setDuplicate(null); }}><Replace size={17} /> Replace device</button></div></Dialog> : null}
    {replaceTarget ? <ReplaceDialog license={replaceTarget} busy={busy} onClose={() => setReplaceTarget(null)} onReplace={async (input) => { const result = await run(() => window.licenseManager.replaceDevice({ licenseId: replaceTarget.id, ...input }), "Replacement license created."); if (result) { setReplaceTarget(null); setIssued(result); setSelected(result); await refresh(); } }} /> : null}
    {renewTarget ? <RenewDialog license={renewTarget} busy={busy} onClose={() => setRenewTarget(null)} onRenew={async (licenseType, administratorNotes) => { const result = await run(() => window.licenseManager.renewLicense({ licenseId: renewTarget.id, deviceId: renewTarget.deviceId, licenseType, administratorNotes }), "Renewal license created."); if (result) { setRenewTarget(null); setIssued(result); setSelected(result); await refresh(); } }} /> : null}
    {issued ? <IssuedDialog license={issued} onClose={() => setIssued(null)} /> : null}
  </section>;
}

function LicenseDetails({ license, busy, run, refresh, onRenew, onReplace, onReissue }: { license: LicenseListItem | null; busy: boolean; run: <T>(operation: () => Promise<T>, success?: string) => Promise<T | undefined>; refresh: () => Promise<void>; onRenew: () => void; onReplace: () => void; onReissue: () => void }) {
  const [revealed, setRevealed] = useState(false);
  const [editOpen, setEditOpen] = useState(false);
  if (!license) return <aside className="detail-panel empty-detail"><KeyRound size={30} /><strong>Select a license</strong><p>Customer, activation, and device history will appear here.</p></aside>;
  const licenseId = license.id;
  async function status(next: Exclude<LicenseStatus, "REPLACED">) { const result = await run(() => window.licenseManager.setLicenseStatus({ licenseId, status: next, notes: `Status changed to ${next}.` }), `License marked ${next.toLowerCase()}.`); if (result) await refresh(); }
  return <aside className="detail-panel"><div className="detail-heading"><div><small>License record</small><h2>{license.customer.customerName}</h2><p>{license.customer.businessName}</p></div><StatusBadge status={license.displayStatus} /></div><dl><dt>Serial number</dt><dd><code>{license.licenseSerialNumber}</code></dd><dt>Device ID</dt><dd><code>{license.deviceId}</code></dd><dt>Product</dt><dd>{license.productName} | {license.edition}</dd><dt>License type</dt><dd>{formatLicenseType(license.licenseType)}</dd><dt>Issue date</dt><dd>{formatDateTime(license.issueDate)}</dd><dt>Expiration</dt><dd>{license.expirationDate ? formatDateTime(license.expirationDate) : "Lifetime"}</dd><dt>Days remaining</dt><dd>{license.daysRemaining === null ? "Unlimited" : license.daysRemaining}</dd><dt>Last modified</dt><dd>{formatDateTime(license.lastModifiedDate)}</dd><dt>Notes</dt><dd>{license.notes || "No notes"}</dd></dl>
    <div className="activation-secret"><div><strong>Activation code</strong><small>Private administrator view</small></div><code>{revealed ? license.activationCode : "************************"}</code><button onClick={() => setRevealed((value) => !value)}>{revealed ? "Hide" : "Reveal"}</button></div>
    <div className="action-grid"><button className="button primary" disabled={busy || license.status === "REPLACED" || license.status === "REVOKED"} onClick={onRenew}><Clock3 size={17} /> Renew license</button><button className="button secondary" disabled={busy} onClick={() => setEditOpen(true)}><Pencil size={17} /> Edit customer</button><button className="button secondary" disabled={busy} onClick={onReissue}><RefreshCw size={17} /> Reissue</button><button className="button secondary" disabled={busy || license.status === "REPLACED"} onClick={onReplace}><Replace size={17} /> Replace</button><button className="button secondary" disabled={busy} onClick={() => void run(() => window.licenseManager.printLicense(license.id), "Print dialog opened.")}><Printer size={17} /> Print</button><button className="button secondary" disabled={busy} onClick={() => void run(() => window.licenseManager.exportLicensePdf(license.id), "Activation PDF saved.")}><FileDown size={17} /> Save PDF</button></div>
    <label>Status<select disabled={busy || license.status === "REPLACED"} value={license.status === "REPLACED" ? "REPLACED" : license.status} onChange={(event) => void status(event.target.value as Exclude<LicenseStatus, "REPLACED">)}><option value="ACTIVE">Active</option><option value="REVOKED">Revoked</option><option value="ARCHIVED">Archived</option>{license.status === "REPLACED" ? <option value="REPLACED">Replaced</option> : null}</select></label>
    {editOpen ? <EditCustomerDialog license={license} busy={busy} onClose={() => setEditOpen(false)} onSave={async (customer) => { if (await run(() => window.licenseManager.saveCustomer(customer), "Customer updated.")) { setEditOpen(false); await refresh(); } }} /> : null}
  </aside>;
}

function EditCustomerDialog({ license, busy, onClose, onSave }: { license: LicenseListItem; busy: boolean; onClose: () => void; onSave: (customer: LicenseListItem["customer"]) => Promise<void> }) {
  const [customer, setCustomer] = useState(license.customer);
  return <Dialog title="Edit customer" onClose={onClose}><form className="form-grid" onSubmit={(event) => { event.preventDefault(); void onSave(customer); }}><label>Customer name<input value={customer.customerName} onChange={(event) => setCustomer({ ...customer, customerName: event.target.value })} required /></label><label>Business name<input value={customer.businessName} onChange={(event) => setCustomer({ ...customer, businessName: event.target.value })} required /></label><label>Contact number<input value={customer.contactNumber} onChange={(event) => setCustomer({ ...customer, contactNumber: event.target.value })} /></label><label>Email<input type="email" value={customer.email} onChange={(event) => setCustomer({ ...customer, email: event.target.value })} /></label><label className="wide">Customer notes<textarea value={customer.notes} onChange={(event) => setCustomer({ ...customer, notes: event.target.value })} rows={4} /></label><div className="dialog-actions wide"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>Save customer</button></div></form></Dialog>;
}

function CreateLicenseDialog({ products, customers, onClose, onCreate, busy }: { products: LicensedProduct[]; customers: ManagerSnapshot["customers"]; onClose: () => void; onCreate: (input: CreateLicenseInput) => Promise<void>; busy: boolean }) {
  const [form, setForm] = useState(blankLicense); const [existing, setExisting] = useState("");
  function choose(id: string) { setExisting(id); const customer = customers.find((entry) => entry.id === id); setForm(customer ? { ...form, customerId: customer.id, customerName: customer.customerName, businessName: customer.businessName, contactNumber: customer.contactNumber, email: customer.email, customerNotes: customer.notes } : { ...form, customerId: undefined, customerName: "", businessName: "", contactNumber: "", email: "", customerNotes: "" }); }
  return <Dialog title="Generate offline license" onClose={onClose}><form className="form-grid" onSubmit={(event) => { event.preventDefault(); void onCreate(form); }}><label className="wide">Existing customer<select value={existing} onChange={(event) => choose(event.target.value)}><option value="">Create a new customer</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.customerName} | {customer.businessName}</option>)}</select></label><label>Customer name<input value={form.customerName} onChange={(event) => setForm({ ...form, customerName: event.target.value })} required readOnly={Boolean(existing)} /></label><label>Business name<input value={form.businessName} onChange={(event) => setForm({ ...form, businessName: event.target.value })} required readOnly={Boolean(existing)} /></label><label>Contact number<input value={form.contactNumber} onChange={(event) => setForm({ ...form, contactNumber: event.target.value })} /></label><label>Email<input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label className="wide">Device ID<input value={form.deviceId} onChange={(event) => setForm({ ...form, deviceId: event.target.value.toUpperCase() })} required spellCheck={false} /></label><label>Product<select value={form.productId} onChange={(event) => setForm({ ...form, productId: event.target.value })}>{products.filter((product) => product.active).map((product) => <option key={product.id} value={product.id}>{product.productName} | {product.edition}</option>)}</select></label><label>License type<select value={form.licenseType} onChange={(event) => setForm({ ...form, licenseType: event.target.value as LicenseType })}><option value="MONTHLY">Monthly</option><option value="YEARLY">Yearly</option><option value="LIFETIME">Lifetime</option></select></label><label>App version<input value={form.appVersion} onChange={(event) => setForm({ ...form, appVersion: event.target.value })} required /></label><label className="wide">License notes<textarea value={form.licenseNotes} onChange={(event) => setForm({ ...form, licenseNotes: event.target.value })} rows={3} placeholder="Payment reference, agreement, or administrator notes" /></label><div className="dialog-actions wide"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}><KeyRound size={17} /> Generate activation</button></div></form></Dialog>;
}

/** Collects the verified Device ID, new term, and permanent administrator notes for a renewal. */
function RenewDialog({ license, busy, onClose, onRenew }: { license: LicenseListItem; busy: boolean; onClose: () => void; onRenew: (licenseType: LicenseType, administratorNotes: string) => Promise<void> }) {
  const [deviceId, setDeviceId] = useState(license.deviceId);
  const [licenseType, setLicenseType] = useState<LicenseType>(license.licenseType);
  const [notes, setNotes] = useState("");
  const matches = deviceId.trim().toUpperCase() === license.deviceId;
  return <Dialog title="Renew license" onClose={onClose}><p>The new signed code replaces the tablet entitlement without erasing the previous license or activation history.</p><form className="form-stack" onSubmit={(event) => { event.preventDefault(); void onRenew(licenseType, notes); }}><label>Verify Device ID<input value={deviceId} onChange={(event) => setDeviceId(event.target.value.toUpperCase())} required spellCheck={false} /></label><label>New license type<select value={licenseType} onChange={(event) => setLicenseType(event.target.value as LicenseType)}><option value="MONTHLY">Monthly</option><option value="YEARLY">Yearly</option><option value="LIFETIME">Lifetime</option></select></label><label>Administrator notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={3} required /></label><div className="dialog-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy || !matches || !notes.trim()}><Clock3 size={17} /> Generate renewal</button></div></form></Dialog>;
}

function ReplaceDialog({ license, busy, onClose, onReplace }: { license: LicenseListItem; busy: boolean; onClose: () => void; onReplace: (input: { newDeviceId: string; appVersion: string; notes: string }) => Promise<void> }) {
  const [deviceId, setDeviceId] = useState(""); const [appVersion, setAppVersion] = useState(license.appVersion); const [notes, setNotes] = useState("");
  return <Dialog title="Replace customer device" onClose={onClose}><p>The old device <code>{license.deviceId}</code> will be marked Replaced. Its record and history remain permanent.</p><form className="form-stack" onSubmit={(event) => { event.preventDefault(); void onReplace({ newDeviceId: deviceId, appVersion, notes }); }}><label>New Device ID<input value={deviceId} onChange={(event) => setDeviceId(event.target.value.toUpperCase())} required /></label><label>App version<input value={appVersion} onChange={(event) => setAppVersion(event.target.value)} required /></label><label>Replacement notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={3} /></label><div className="dialog-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}><Replace size={17} /> Generate replacement</button></div></form></Dialog>;
}

function IssuedDialog({ license, onClose }: { license: LicenseListItem; onClose: () => void }) {
  const [qr, setQr] = useState(""); useEffect(() => { void QRCode.toDataURL(JSON.stringify({ deviceId: license.deviceId, activationCode: license.activationCode }), { width: 280, margin: 1 }).then(setQr); }, [license]);
  return <Dialog title="Activation ready" onClose={onClose}><div className="issued"><div>{qr ? <img src={qr} alt="Activation QR code" /> : <RefreshCw className="spin" />}<small>Scan on the matching Android tablet</small></div><section><p><strong>{license.customer.customerName}</strong><br />{license.productName} | {license.edition}</p><label>License<code>{formatLicenseType(license.licenseType)} | {license.expirationDate ? `Expires ${formatDate(license.expirationDate)}` : "Lifetime"}</code></label><label>Device ID<code>{license.deviceId}</code></label><label>Activation code<code className="long-code">{license.activationCode}</code></label><div className="dialog-actions"><button className="button secondary" onClick={() => void navigator.clipboard.writeText(license.activationCode)}><Download size={17} /> Copy code</button><button className="button secondary" onClick={() => void window.licenseManager.printLicense(license.id)}><Printer size={17} /> Print sheet</button><button className="button primary" onClick={onClose}><Check size={17} /> Done</button></div></section></div></Dialog>;
}

function HistoryView({ snapshot }: { snapshot: ManagerSnapshot }) {
  const [search, setSearch] = useState(""); const events = snapshot.activationEvents.filter((event) => !search.trim() || [event.customerName, event.deviceId, event.type, event.softwareVersion].some((value) => value.toLowerCase().includes(search.toLowerCase()))).sort((a, b) => b.timestamp.localeCompare(a.timestamp));
  return <section className="screen"><header className="screen-header"><div><p className="eyebrow">Permanent audit trail</p><h1>Activation history</h1><p>Generation, renewal, reissue, replacement, revocation, archival, and import events are never deleted.</p></div></header><div className="toolbar"><label className="search"><Search size={18} /><input placeholder="Search history" value={search} onChange={(event) => setSearch(event.target.value)} /></label><span>{events.length} events</span></div><div className="table-panel"><table><thead><tr><th>Timestamp</th><th>Event</th><th>Customer</th><th>Device ID</th><th>Type</th><th>Old expiration</th><th>New expiration</th><th>Notes</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td>{formatDateTime(event.timestamp)}</td><td><b>{event.type}</b></td><td>{event.customerName}</td><td><code>{event.deviceId}</code></td><td>{formatLicenseType(event.licenseType)}</td><td>{event.oldExpirationDate ? formatDate(event.oldExpirationDate) : "-"}</td><td>{event.newExpirationDate ? formatDate(event.newExpirationDate) : "Lifetime"}</td><td>{event.notes || "-"}</td></tr>)}</tbody></table>{events.length === 0 ? <Empty icon={History} text="No activation events yet." /> : null}</div></section>;
}

function SettingsView({ snapshot, busy, run, refresh }: { snapshot: ManagerSnapshot; busy: boolean; run: <T>(operation: () => Promise<T>, success?: string) => Promise<T | undefined>; refresh: () => Promise<void> }) {
  const [branding, setBranding] = useState(snapshot.branding); const [preferences, setPreferences] = useState(snapshot.preferences); const [passwords, setPasswords] = useState({ currentPassword: "", newPassword: "" }); const [restorePassword, setRestorePassword] = useState(""); const [product, setProduct] = useState({ productName: "", productVersion: "1.0", edition: "Standard", active: true });
  async function saveBranding(event: FormEvent) { event.preventDefault(); if (await run(() => window.licenseManager.saveBranding(branding), "Branding saved.")) await refresh(); }
  async function savePreferences(event: FormEvent) { event.preventDefault(); if (await run(() => window.licenseManager.savePreferences(preferences), "Security preferences saved.")) await refresh(); }
  async function logo(file: File | undefined) { if (!file) return; if (file.size > 2_000_000) return; const data = await file.arrayBuffer(); const binary = new Uint8Array(data).reduce((value, byte) => value + String.fromCharCode(byte), ""); setBranding({ ...branding, logoDataUrl: `data:${file.type};base64,${btoa(binary)}` }); }
  return <section className="screen"><header className="screen-header"><div><p className="eyebrow">Owner controls</p><h1>Settings and recovery</h1><p>Branding, encrypted backups, spreadsheet exchange, products, and automatic lock.</p></div></header><div className="settings-columns">
    <form className="settings-section form-stack" onSubmit={saveBranding}><h2><Building2 size={20} /> Activation-sheet branding</h2>{branding.logoDataUrl ? <img className="logo-preview" src={branding.logoDataUrl} alt="Company logo" /> : null}<label>Company logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => void logo(event.target.files?.[0])} /></label><label>Company name<input value={branding.companyName} onChange={(event) => setBranding({ ...branding, companyName: event.target.value })} required /></label><label>Contact information<textarea value={branding.contactInformation} onChange={(event) => setBranding({ ...branding, contactInformation: event.target.value })} rows={4} /></label><button className="button primary" disabled={busy}>Save branding</button></form>
    <section className="settings-section form-stack"><h2><Backup size={20} /> Backup and exchange</h2><p>Backups are encrypted with the administrator password and include the private signing key. Keep at least two off-PC copies.</p><button className="button primary" disabled={busy} onClick={() => void run(() => window.licenseManager.manualBackup(), "Encrypted backup exported.")}><Backup size={18} /> Manual encrypted backup</button><label>Backup password for restore<input type="password" minLength={12} value={restorePassword} onChange={(event) => setRestorePassword(event.target.value)} /></label><button className="button danger" disabled={busy || restorePassword.length < 12} onClick={async () => { if (await run(() => window.licenseManager.restoreBackup(restorePassword), "Encrypted backup restored.")) await refresh(); }}><RefreshCw size={18} /> Restore backup</button><div className="button-row"><button className="button secondary" onClick={() => void run(() => window.licenseManager.exportCsv(), "CSV exported.")}><FileDown size={17} /> CSV</button><button className="button secondary" onClick={() => void run(() => window.licenseManager.exportExcel(), "Excel workbook exported.")}><FileSpreadsheet size={17} /> Excel</button><button className="button secondary" onClick={async () => { const result = await run(() => window.licenseManager.importSpreadsheet()); if (result) { await refresh(); } }}><Download size={17} /> Import</button></div></section>
    <form className="settings-section form-stack" onSubmit={savePreferences}><h2><Clock3 size={20} /> Security</h2><label>Automatic lock (minutes)<input type="number" min="1" max="120" value={preferences.autoLockMinutes} onChange={(event) => setPreferences({ ...preferences, autoLockMinutes: Number(event.target.value) })} /></label><label className="toggle"><input type="checkbox" checked={preferences.autoBackup} onChange={(event) => setPreferences({ ...preferences, autoBackup: event.target.checked })} /> Automatic encrypted backup after every change</label><button className="button primary" disabled={busy}>Save security settings</button><hr /><h3>Change administrator password</h3><label>Current password<input type="password" value={passwords.currentPassword} onChange={(event) => setPasswords({ ...passwords, currentPassword: event.target.value })} /></label><label>New password<input type="password" minLength={12} value={passwords.newPassword} onChange={(event) => setPasswords({ ...passwords, newPassword: event.target.value })} /></label><button type="button" className="button secondary" disabled={busy || passwords.currentPassword.length < 12 || passwords.newPassword.length < 12} onClick={() => void run(() => window.licenseManager.changePassword(passwords), "Administrator password changed.")}><Lock size={17} /> Change password</button></form>
    <section className="settings-section form-stack"><h2><PackagePlus size={20} /> Licensed products</h2><div className="product-list">{snapshot.products.map((entry) => <div key={entry.id}><strong>{entry.productName}</strong><span>{entry.productVersion} | {entry.edition}</span></div>)}</div><label>Product name<input value={product.productName} onChange={(event) => setProduct({ ...product, productName: event.target.value })} /></label><div className="button-row"><label>Version<input value={product.productVersion} onChange={(event) => setProduct({ ...product, productVersion: event.target.value })} /></label><label>Edition<input value={product.edition} onChange={(event) => setProduct({ ...product, edition: event.target.value })} /></label></div><button className="button secondary" disabled={busy || !product.productName.trim()} onClick={async () => { if (await run(() => window.licenseManager.addProduct(product), "Product added.")) { setProduct({ productName: "", productVersion: "1.0", edition: "Standard", active: true }); await refresh(); } }}><Plus size={17} /> Add product</button></section>
  </div></section>;
}

function Dialog({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button aria-label="Close" onClick={onClose}><X size={20} /></button></header><div className="modal-body">{children}</div></section></div>; }
function StatusBadge({ status }: { status: LicenseDisplayStatus }) { return <span className={`status status-${status.toLowerCase().replaceAll("_", "-")}`}>{status.toLowerCase().replaceAll("_", " ")}</span>; }
function Empty({ icon: Icon, text }: { icon: typeof Archive; text: string }) { return <div className="empty"><Icon size={28} /><p>{text}</p></div>; }
function formatDate(value: string) { return new Date(value).toLocaleDateString(); }
function formatDateTime(value: string) { return new Date(value).toLocaleString(); }
function formatLicenseType(value: LicenseType) { return value[0] + value.slice(1).toLowerCase(); }
